Autod/Models/Auto/AutoListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Autod.Models.Auto
{
    public class AutoListViewModel
    {
        public Guid? Id { get; set; }
        public string Mark { get; set; }
        public string Modell { get; set; }
        public double Price { get; set; }
        public int Ammount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }
    }
}

Autod/Models/Auto/AutoViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using Autod.Models.Files;

namespace Autod.Models.Auto
{
    public class AutoViewModel
    {
        public Guid? Id { get; set; }
        public string Mark { get; set; }
        public string Modell { get; set; }
        public double Price { get; set; }
        public int Amount { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime ModifiedAt { get; set; }

        public List<IFormFile> Files { get; set; }

        public List<ExistingFilePathViewModel> ExistingFilePaths { get; set; } = new List<ExistingFilePathViewModel>();
    }
}

Autod/Models/ErrorViewModel.cs
using System;

namespace Autod.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Autod/Models/Files/ExistingFilePathViewModel.cs
using System;


namespace Autod.Models.Files
{
    public class ExistingFilePathViewModel
    {
        public Guid PhotoId { get; set; }
        public string FilePath { get; set; }
        public Guid AutoId { get; set; }
    }
}

Autod/Controllers/AutoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;
using Autod.Core.Dtos;
using Autod.Core.ServiceInterface;
using Autod.Data;
using Autod.Models.Files;
using Autod.Models.Auto;

namespace Autod.Controllers
{
    public class AutoController : Controller
    {
        private readonly AutodDbContext _context;
        private readonly IAutoService _autoService;
        private readonly IFileServices _fileService;

        public AutoController
            (
                AutodDbContext context,
                IAutoService autoService,
                IFileServices fileService
            )
        {
            _context = context;
            _autoService = autoService;
            _fileService = fileService;
        }


        public IActionResult Index()
        {
            var result = _context.Auto
                .Select(x => new AutoListViewModel
                {
                    Id = x.Id,
                    Mark = x.Mark,
                    Price = x.Price,
                    Ammount = x.Amount,
                    Modell = x.Modell
                });

            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            var auto = await _autoService.Delete(id);

            if (auto == null)
            {
                RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Add()
        {
            AutoViewModel model = new AutoViewModel();

            return View("Edit", model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AutoViewModel model)
        {
            var dto = new AutoDto()
            {
                Id = model.Id,
                Modell = model.Modell,
                Mark = model.Mark,
                Amount = model.Amount,
                Price = model.Price,
                ModifiedAt = model.ModifiedAt,
                CreatedAt = model.CreatedAt,
                Files = model.Files,
                ExistingFilePaths = model.ExistingFilePaths
                    .Select(x => new ExistingFilePathDto
                    {
                        PhotoId = x.PhotoId,
                        FilePath = x.FilePath,
                        AutoId = x.AutoId
                    }).ToArray()
            };

            var result = await _autoService.Add(dto);
            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var auto = await _autoService.Edit(id);
            if (auto == null)
            {
                return NotFound();
            }

            var photos = await _context.ExistingFilePath
                .Where(x => x.AutoId == id)
                .Select(y => new ExistingFilePathViewModel
                {
                    FilePath = y.FilePath,
                    PhotoId = y.Id
                })
                .ToArrayAsync();


            var model = new AutoViewModel();

            model.Id = auto.Id;
            model.Modell = auto.Modell;
            model.Mark = auto.Mark;
            model.Amount = auto.Amount;
            model.Price = auto.Price;
            model.ModifiedAt = auto.ModifiedAt;
            model.CreatedAt = auto.CreatedAt;
            model.ExistingFilePaths.AddRange(photos);

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Update(AutoViewModel model)
        {
            var dto = new AutoDto()
            {
                Id = model.Id,
                Modell = model.Modell,
                Mark = model.Mark,
                Amount = model.Amount,
                Price = model.Price,
                ModifiedAt = model.ModifiedAt,
                CreatedAt = model.CreatedAt,
                Files = model.Files,
                ExistingFilePaths = model.ExistingFilePaths
                    .Select(x => new ExistingFilePathDto
                    {
                        PhotoId = x.PhotoId,
                        FilePath = x.FilePath,
                        AutoId = x.AutoId
                    }).ToArray()
            };

            var result = await _autoService.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index), model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveImage(ExistingFilePathViewModel model)
        {
            var dto = new ExistingFilePathDto()
            {
                FilePath = model.FilePath
            };

            var image = await _fileService.RemoveImage(dto);
            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

Autod/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Autod.Models;

namespace Autod.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Autod/Views/Auto/Edit.cshtml
@model Autod.Models.Auto.AutoViewModel


@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Add</h1>
}



<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Mark" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Mark" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Modell" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <textarea asp-for="Modell" class="form-control" rows="5"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Price" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Amount" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Amount" class="form-control" />
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input class="form-control custom-file-input" asp-for="Files" multiple type="file" />
                    <label class="custom-file-label">Choose file...</label>
                </div>
            </div>
        </div>

        @foreach (var photo in Model.ExistingFilePaths)
        {
            <partial name="_Photo" model="photo" />
        }

        @if (Model.Id.HasValue)
        {
            <input asp-action="update" asp-controller="auto" type="submit" class="btn btn-primary" value="Update">
            <input asp-action="delete" asp-controller="auto" asp-for="Id" type="submit" class="btn btn-danger" value="Delete">
        }
        else
        {
            <input asp-action="add" asp-controller="auto" type="submit" class="btn btn-primary" value="Add">
        }
        <a asp-action="index" class="btn btn-primary">Index</a>

    </form>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.custom-file-input').on("change", function () {
                var fileLabel = $(this).next('.custom-file-label');
                var files = $(this)[0].files;
                if (files.length > 1) {
                    fileLabel.html(files.length + ' files selected');
                }
                else if (files.length == 1) {
                    fileLabel.html(files[0].name);
                }
                //$(this).next('.custom-file-label').html(fileLabel);
            });
        });
    </script>
}

Autod/Views/Auto/Index.cshtml
@model IEnumerable<Autod.Models.Auto.AutoListViewModel>

@{ 
    int queueNumber = 0;
}

<div>
    <a asp-action="add" asp-controller="auto" type="submit" class="btn btn-danger">Add</a>
</div>
<form method="post">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nr</th>
                <th scope="col">Mark</th>
                <th scope="col">Model</th>
                <th scope="col">Price</th>
                <th scope="col">Ammount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var auto in Model)
            {
                queueNumber++;

                <tr>
                    <td class="">@queueNumber</td>
                    <td class="">@auto.Mark</td>
                    <td class="">@auto.Modell</td>
                    <td class="">@auto.Price</td>
                    <td class="">@auto.Ammount</td>
                    <td>
                        <a asp-action="edit" asp-controller="auto" asp-route-id="@auto.Id" class="btn btn-primary">Edit</a>
                        <input asp-action="delete" asp-controller="auto" asp-route-id="@auto.Id" type="submit" class="btn btn-danger" value="Delete">
                    </td>


                </tr>
            }
        </tbody>
    </table>
</form>

Autod/Views/Auto/_Photo.cshtml
@model Autod.Models.Files.ExistingFilePathViewModel

@{
    var photoPaths = "~/multipleFileUpload/" + (Model.FilePath ?? "noimage.jpg");
}

<div class="form-group row col-sm-4 offset-2">
    <img class="card-img-top" src="@photoPaths" asp-append-version="true" />
    <input asp-action="removeImage" asp-controller="auto" asp-route-filePath="@Model.FilePath" type="submit" class="btn btn-danger" value="Remove Image" />
</div>

Autod/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Autod/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Autod</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Autod</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Auto" asp-action="Index">Auto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @DateTime.Now.Year - Autod - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>